variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 2

stages:
  - build
  - test

.build_template: &build_template
  tags:
    - xilinx
  stage: build
  image: registry.esss.lu.se/ics-docker/vivado:${VIVADO_VER}
  artifacts:
    paths:
      - fpga/output/build/binaries
    expire_in: 8 week
  when: always

build-dev:
  <<: *build_template
  script:
    - make
    - TS=yes make stamp
  when: manual

build-tag:
  <<: *build_template
  script:
    - make
    - make stamp
  only:
    - tags

test:
  tags:
    - xilinx
  stage: test
  image: registry.esss.lu.se/ics-docker/vivado:${VIVADO_VER}
  artifacts:
    paths:
      - sw/test/iladata.csv
    expire_in: 1 week
  script:
    - python3.7 -m venv venv
    - source venv/bin/activate
    - pip install pandas
    - python sw/test/TestRunner.py sw/test/iladata.csv rx_data ${TEST_EVENT_CODE} --acq ${ACQ_TCL}
  when: manual
